### ISSUE TITLE
Source of language data not in repo?

### ISSUE THREAD

**Issue by DonaldTsang** [peterkahl/language-genius#1]
Sorry for asking, but why can't I find all 70 language's N-grams in the repo?

**Comment by peterkahl** [comment]
The ones I added are not in the library. Hence the need for my wrapper.

**Comment by DonaldTsang** [comment]
Source of the repo for the 70 languages?

**Comment by peterkahl** [comment]
I don't understand your question. If you are looking for N-grams of 70 languages, it is not here.

**Comment by DonaldTsang** [comment]
Both the Ngrams and the source corpus that generates the Ngrams, that is outside this repo but used by this repo.
